"""empty message

Revision ID: fdb953976ffb
Revises: 
Create Date: 2021-05-02 00:24:29.732781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb953976ffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lianjia_city_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_name_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lianjia_village_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('village_url', sa.String(length=300), nullable=False),
    sa.Column('village_name', sa.String(length=64), nullable=False),
    sa.Column('village_addr', sa.String(length=64), nullable=False),
    sa.Column('village_detail_addr', sa.String(length=128), nullable=False),
    sa.Column('village_year', sa.String(length=128), nullable=False),
    sa.Column('village_building_type', sa.String(length=128), nullable=False),
    sa.Column('village_developer', sa.String(length=128), nullable=False),
    sa.Column('village_property_charges_min', sa.String(length=128), nullable=False),
    sa.Column('village_property_charges_max', sa.String(length=128), nullable=False),
    sa.Column('village_building_blocks_num', sa.String(length=128), nullable=False),
    sa.Column('village_door', sa.String(length=128), nullable=False),
    sa.Column('village_longitude', sa.String(length=128), nullable=False),
    sa.Column('village_latitude', sa.String(length=128), nullable=False),
    sa.Column('village_sale_num', sa.String(length=32), nullable=False),
    sa.Column('village_access_rate', sa.String(length=32), nullable=False),
    sa.Column('village_green_rate', sa.String(length=128), nullable=False),
    sa.Column('village_plot_ratio', sa.String(length=128), nullable=False),
    sa.Column('village_score', sa.String(length=32), nullable=False),
    sa.Column('traffic_name_info', sa.String(length=1280), nullable=False),
    sa.Column('traffic_distance_info', sa.String(length=1280), nullable=False),
    sa.Column('hospital_name_info', sa.String(length=1280), nullable=False),
    sa.Column('hospital_distance_info', sa.String(length=1280), nullable=False),
    sa.Column('park_name_info', sa.String(length=1280), nullable=False),
    sa.Column('park_distance_info', sa.String(length=1280), nullable=False),
    sa.Column('market_name_info', sa.String(length=1280), nullable=False),
    sa.Column('market_distance_info', sa.String(length=1280), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['lianjia_city_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lianjia_village_price_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=128), nullable=False),
    sa.Column('month', sa.String(length=128), nullable=False),
    sa.Column('village_unit_price', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['lianjia_village_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lianjia_village_price_info')
    op.drop_table('lianjia_village_info')
    op.drop_table('user_name_info')
    op.drop_table('lianjia_city_info')
    # ### end Alembic commands ###
